image: docker:20.10

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: alessandromariani160381/billmanager-webapp
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  stage: build
  script:
    - echo "Docker image:"
    - echo $DOCKER_IMAGE
    - echo "Docker tag:"
    - echo $DOCKER_TAG
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  only:
    - master

push:
  stage: push
  script:
    - echo "Docker image:"
    - echo $DOCKER_IMAGE
    - echo "Docker tag:"
    - echo $DOCKER_TAG
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - master
