image: google/cloud-sdk:latest  # Usa l'immagine Docker di Google Cloud SDK

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: alessandromariani160381/billmanager-webapp
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA

before_script:
  - apt-get update && apt-get install -y docker.io
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build_and_push:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker images # Mostra le immagini per il debug
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - echo "$GCLOUD_SERVICE_KEY" > /gcloud-key.json
    - gcloud auth activate-service-account --key-file=/gcloud-key.json
    - gcloud config set project bill-manager-kubernetes  # Cambia con il tuo ID progetto

  only:
    - master
