image: docker:20.10

services:
  - docker:dind

stages:
  - build
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: alessandromariani160381/billmanager-webapp
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA

before_script:
  - apk add --no-cache bash curl python3 py3-pip
  - curl -sSL https://sdk.cloud.google.com | bash
  - export PATH="$PATH:/root/google-cloud-sdk/bin"  # Aggiungi gcloud al PATH
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build_and_push:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker images
    - docker push $DOCKER_IMAGE:$DOCKER_TAG

deploy:
  stage: deploy
  script:
    - export PATH="$PATH:/root/google-cloud-sdk/bin"  # Assicurati che gcloud sia nel PATH
    - printf "%s" "$GCLOUD_SERVICE_KEY" > /gcloud-key.json
    - cat /gcloud-key.json
    - python3 -c "import json; json.load(open('/gcloud-key.json'))" || echo "Errore nel JSON"
    - gcloud auth activate-service-account --key-file=/gcloud-key.json
    - gcloud container clusters get-credentials billmanager-cluster --zone europe-west1-b --project bill-manager-kubernates
    - sed -i "s|image:.*|image:${DOCKER_IMAGE}:${DOCKER_TAG}|" webapp-deployment.yaml
    - kubectl apply -f webapp-deployment.yaml
  only:
    - master
