stages:
  - build
  - push

variables:
  DOCKER_IMAGE: alessandromariani160381/billmanager-webapp
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  only:
    - master

push:
  stage: push
  script:
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - master
